ProjektGrupa/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import (TeamsListView, TeamCreateView, TaskUpdateView,
                        TeamMemberCreateView, TeamMemberDeleteView,
                        TaskDeleteView,
                        )
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', TeamsListView.as_view(), name='user_dashboard'),
    path('team_panel/<int:pk>/', include('main.urls')),
    path('team_add/', TeamCreateView.as_view(), name='team_add'),
    path('message/', include('message.urls')),

    path('chat/<int:pk>/', include('chat.urls')),

    path('member_delete/<int:pk>', TeamMemberDeleteView.as_view(), name='member_delete'),
    path('task_delete/<int:pk>', TaskDeleteView.as_view(), name='task_delete'),
    path('task_end/<int:pk>', TaskUpdateView.as_view(), name='task_end'),
    # path('task_end/<int:pk>', TaskUpdateView.as_view(), name='task_end')

]

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import MySignUpView, MyLoginView, MyPasswordChangeView

app_name = 'accounts'
urlpatterns = [
    path('signup/', MySignUpView.as_view(), name='signup'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('change_password', MyPasswordChangeView.as_view(), name='change-password')
]

chat/urls.py
from django.urls import path
from .views import ChatMessagesListView, ChatMessagesCreateView

app_name = 'chat'

urlpatterns = [
    path('', ChatMessagesListView.as_view(), name="chat"),
    path('new/', ChatMessagesCreateView.as_view(), name="new")
]

message/urls.py
from django.urls import path
from .views import MessageListView, MessageCreateView, ContentCreateView


urlpatterns = [
    path('', MessageListView.as_view(), name="MessListView"),
    path('create/', MessageCreateView.as_view(), name="MessCreateView"),
    path('create_to/<int:pk>', ContentCreateView.as_view(), name='message_to')
]

chat/models.py
from django.db import models
from main.models import Teams
from accounts.models import Users


# Create your models here.

class ChatMessages(models.Model):

    chat_number = models.ForeignKey('Chats', on_delete=models.CASCADE)
    member_name = models.ForeignKey(Users, on_delete=models.DO_NOTHING)
    message = models.CharField(max_length=1000)
    time_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.time_sent.strftime("%Y-%m-%d %H:%M:%S") + " " + str(self.member_name) + ": " + self.message

      
class Chats(models.Model):
    team_name = models.ForeignKey(Teams, on_delete=models.CASCADE)
    # message_text = models.ForeignKey(ChatMessages, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "Chat: " + str(self.team_name)

# class Meta:
#        ordering = ['time_sent']
#        message = models.CharField(max_length=1000)

message/models.py
from django.db import models
from accounts.models import Users
# Create your models here.
class Messages(models.Model):
    id_user_from = models.ForeignKey(Users, on_delete=models.DO_NOTHING, related_name='message_from')
    id_user_to = models.ForeignKey(Users, models.DO_NOTHING, related_name='message_to')
    content = models.CharField(max_length=1000)
    sent_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.content

chat/views.py
# from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import ChatMessages, Chats
# from chat.models import Chats
# from django.db.models import CharField, Model
from django.urls import reverse_lazy


# Create your views here.

class ChatMessagesListView(ListView):
    template_name = "chat.html"
    model = ChatMessages

    def get_queryset(self):
        filter1 = Chats.objects.get(team_name=self.kwargs['pk'])
        self.extra_context = {'chat': Chats.objects.get(team_name=self.kwargs['pk'])}
        return ChatMessages.objects.filter(chat_number=filter1)


class ChatMessagesCreateView(CreateView):
    template_name = "form.html"
    model = ChatMessages
    fields = ["message"]
    # success_url = reverse_lazy("user_dashboard")

    def form_valid(self, form):
        form.instance.chat_number = Chats.objects.get(team_name=self.kwargs['pk'])
        form.instance.member_name = self.request.user.users
        return super(ChatMessagesCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("chat:chat", kwargs={'pk': self.kwargs['pk']})

message/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import Messages
from accounts.models import Users
from main.models import TeamMembers
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class MessageListView(LoginRequiredMixin, ListView):
    model = Messages
    template_name = "message.html"

    def get_queryset(self):
        self.extra_context = {'to': Messages.objects.filter(id_user_from=self.request.user.users)}
        return Messages.objects.filter(id_user_to=self.request.user.users)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Messages
    template_name = "form.html"
    fields = ['content', 'id_user_to']
    success_url = reverse_lazy("MessListView")

    def form_valid(self, form):
        form.instance.id_user_from = self.request.user.users
        return super(MessageCreateView, self).form_valid(form)


class ContentCreateView(LoginRequiredMixin, CreateView):
    model = Messages
    template_name = "form.html"
    fields = ['content']
    success_url = reverse_lazy("MessListView")

    def form_valid(self, form):
        form.instance.id_user_from = self.request.user.users
        user_pk = TeamMembers.objects.get(pk=self.request.resolver_match.kwargs['pk']).member_name
        form.instance.id_user_to = Users.objects.get(pk=user_pk.id)
        return super(ContentCreateView, self).form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/"><b>ProMan</b></a>
            {% if user.is_authenticated %}
                <a style="color: white"><b>Hello {{ user }}!</b></a>
                <a class="nav-item active text-right" href="{% url 'accounts:logout' %}">Log Out</a>
                <a class="nav-item nav-link active" href="{% url 'MessListView' %}">Messages</a>
            {% else %}
                <a class="nav-item active text-right" href="{% url 'accounts:signup' %}">Register</a>
               <a class="nav-item active text-right" href="{% url 'accounts:login' %}">Log In</a>
                <a class="nav-item active text-right" href="{% url 'accounts:change-password' %}">Change password</a>
            {% endif %}
        </div>

    </nav>

    <div class="container">
        <div class="jumbotron">
            {% block content %}
            {% endblock %}

        </div>
    </div>
</body>
</html>

templates/chat.html
{% extends 'base.html' %}
{% block content %}
    {% for message in object_list %}

        <p>{{ message }}</p>

    {% endfor %}

    <a class="btn btn-primary" href="{% url 'chat:new' chat.team_name.id %}">Add message</a>

{% endblock %}

templates/delete.html
{% extends 'base.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this item?</p>
        <input type="submit" value="Submit" class="btn btn-danger">
    </form>

{% endblock %}

templates/form.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1> {{ welcome }} </h1>
{% endblock %}

templates/message.html
{% extends "base.html" %}
{% block content %}

    <div class="row align-items-start">
        <div class="col">
            <h6>INBOX</h6>
            {% for message_from in object_list %}
                <p>From: {{ message_from.id_user_from }}, message: {{ message_from }}</p>
            {% endfor %}

        </div>

        <div class="col">
            <h6>OUTBOX</h6>
            {% for message_to in to %}
                <p>To: {{ message_to.id_user_to }}, message: {{ message_to }}</p>
            {% endfor %}

        </div>
    </div>
    <br>
    <a href="{% url 'MessCreateView' %}" class="btn btn-primary">New Message</a>

{% endblock %}

templates/tasks_list.html
{% extends 'base.html' %}

{% block content %}

    {% for task in object_list %}

        <p><a href="">{{ task }}</a>
        <a href="{% url 'task_end' task.id %}" class="btn btn-primary">End</a>
        <a href="{% url 'task_delete' task.id %}" class="btn btn-primary">Delete</a>
        </p>

    {% endfor %}

{% endblock %}

templates/team_add_form.html
{% extends 'base.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
      {{ form }}

      {% for formset in inlines %}
        {{ formset }}
      {% endfor %}

      <input type="submit" value="Submit" />
    </form>

{% endblock %}

templates/team_members_list.html
{% extends 'base.html' %}

{% block content %}
    <h1 align="center"><b>{{ team }}</b></h1>
    <div class="row align-items-start">
        <div class="col">
            <p>Manager: {{ team.manager }}
                {% if user.is_superuser %}
                <a href="{% url 'manager_change' team.id %}" class="btn btn-primary">Change</a>
                {% endif %}
            </p>
{#            <p>{{ user_id }}, {{ team.manager.id }}</p>#}
            {% for member in object_list %}
                <p>
                    <a href="">{{ member.member_name }}</a>
                    {% if user_id == team.manager.id or user.is_superuser %}
                        <a href="{% url 'member_delete' member.id %}" class="btn btn-primary">Delete</a>
                        <a href="{% url 'member_tasks' team.id %}" class="btn btn-primary">Change User's Tasks</a>
                        <a href="{% url 'message_to' member.id %}" class="btn btn-primary">Send Message</a>
                    {% else %}
                        <a href="{% url 'message_to' member.id %}" class="btn btn-primary">Send Message</a>
                    {% endif %}
                </p>
            {% endfor %}

        </div>

        <div class="col">
            {% for task in tasks %}
                <p>{{ task }}
                    {% if user_id == team.manager.id or user.is_superuser %}
                        <a href="{% url 'task_end' task.id %}" class="btn btn-primary">End</a>
                        <a href="{% url 'task_delete' task.id %}" class="btn btn-primary">Delete</a>
                    {% endif %}
                </p>

            {% endfor %}
        </div>
    </div>
        {% if user.is_superuser %}
            <a href="{% url 'task_add' team.id %}" class="btn btn-primary">Add Task</a>
            <a href="{% url 'team_delete' team.id %}" class="btn btn-danger">Team Delete</a>
            <a href="{% url 'member_add' team.id %}" class="btn btn-primary">Add member</a>
            <a href="{% url 'chat:chat' chat.id %}" class="btn btn-primary">Chat</a>
        {% elif user_id == team.manager.id %}
            <a href="{% url 'task_add' team.id %}" class="btn btn-primary">Add Task</a>
            <a href="{% url 'member_add' team.id %}" class="btn btn-primary">Add member</a>
        {% else %}
            <a href="{% url 'chat:chat' team.id %}" class="btn btn-primary">Chat</a>
        {% endif %}

{% endblock %}

templates/teams_list.html
{% extends 'base.html' %}

{% block content %}
{#    <p>{{ user.id }}</p>#}
{#    {% for member in members %}#}
{#        <p>{{ member.team_name }}: {{ member.member_name }}, {{ member.member_name.id }}</p>#}
{#    {% endfor %}#}
{##}
{#    {% for user in all_users %}#}
{#        <p>{{ user }}, {{ user.id }}</p>#}
{#    {% endfor %}#}





    <div class="row align-items-start">
        {% for team in object_list %}
            <div class="col">
                <a href="{% url 'team_dashboard' team.id %}">{{ team }}</a>
            </div>
        {% endfor %}

    {% if user.is_superuser %}
        <div class="col">
            <a href="{% url 'team_add' %}" class="btn btn-primary">Add team</a>
        </div>
    {% else %}
    {% endif %}
    </div>
{% endblock %}